//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralBonus.SubscribeMailer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubscribeMailer.SubscribeMailerSoap")]
    public interface SubscribeMailerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ADD(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADD", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ADDAsync(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mailer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Mailer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mailer", ReplyAction="*")]
        System.Threading.Tasks.Task MailerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscribeMailerSoapChannel : ReferralBonus.SubscribeMailer.SubscribeMailerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscribeMailerSoapClient : System.ServiceModel.ClientBase<ReferralBonus.SubscribeMailer.SubscribeMailerSoap>, ReferralBonus.SubscribeMailer.SubscribeMailerSoap {
        
        public SubscribeMailerSoapClient() {
        }
        
        public SubscribeMailerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscribeMailerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscribeMailerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscribeMailerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ADD(int i, int j) {
            return base.Channel.ADD(i, j);
        }
        
        public System.Threading.Tasks.Task<int> ADDAsync(int i, int j) {
            return base.Channel.ADDAsync(i, j);
        }
        
        public void Mailer() {
            base.Channel.Mailer();
        }
        
        public System.Threading.Tasks.Task MailerAsync() {
            return base.Channel.MailerAsync();
        }
    }
}
